### ISSUE TITLE
大佬，方便写个教程么

### ISSUE THREAD

**Issue by nhgoodboy** [shenxingchao/vue-admin-thinkphp#1]

**Comment by shenxingchao** [comment]
写了个简易教程在readme里

**Comment by djknight1** [comment]
@shenxingchao 已star 757389099@qq.com

**Comment by Tiamo1221** [comment]
已star 25963898@qq.com

**Comment by hs364** [comment]
你好  数据库在哪里呢？  很急很急 想参考一下

**Comment by hs364** [comment]
3.sql下载地址：https://pan.baidu.com/s/1_yFKpMJfmm-yURQb_RXNpw 密码：star后留下邮箱获取（防止伸手党） 这个不对呢

**Comment by WYCang** [comment]
824883748@qq.com 已star ，感谢分享

**Comment by renjunchi** [comment]
395278118@qq.com 已star ，感谢分享

**Comment by ctmum** [comment]
楼主你好，怎样让前台独立运行？？
