### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by nasasky** [shenxingchao/vue-admin-thinkphp#13]
你好，能不能发一下数据库文件给我，谢谢
邮箱：284308203@qq.com

**Comment by zjdboy** [comment]
zjdboy@163.com
 你好，数据库文件，谢谢

**Comment by wzs28150** [comment]
已star 求数据库 1003418012@qq.com

**Comment by Kaelalv** [comment]
已star ，求数据库 1025746266@qq.com
