### ISSUE TITLE
star了 求数据库

### ISSUE THREAD

**Issue by CCGyyn** [shenxingchao/vue-admin-thinkphp#8]
邮箱：1107079145@qq.com

**Comment by machuangchuang** [comment]
数据库:存放数据的仓库。是依照某种数据模型进行组织并存放到储存器的数据集合。
数据库包括：视频，音频，文本文件。
数据库的使用对象：购物网站，娱乐网站，金融机构......
提供数据库管理的软件：    甲骨文的     Oracle  ,  Database  ,  mysql (mariadb)   
                                             Microsoft的   SQL server  ,   access     (这个公司的软件不支持跨平台)
                                             IBM 的         db2
                                              mybase的   mybase
                                              伯克利大学的  PostgreSQL
